### ISSUE TITLE
[semantic_graph_slam_node-9] process has died 

### ISSUE THREAD

**Issue by He-Rong** [hridaybavle/semantic_slam#2]
Hi, I have finished all the steps following the instructions and nothing goes wrong.
But when I run
```
roslaunch semantic_SLAM ps_slam_with_snap_pose_bucket_det_lab_data_with_octomap.launch bagfile:=${HOME}/Downloads/entire_lab_3_rounds.bag show_rviz:=true
```

I get errors like this.
```# Using CSparse poseDim -1 landMarkDim -1 blockordering 0
done
keyframe_delta_trans 0.5
keyframe_delta_angle 0.5
keyframe_delta_time 1
use_const_inf_matrix: 1
const_stddev_x: 0.00667
const_stddev_q: 1e-05
camera angle in radians: 0.59219
update keyframe every detection: 1
add first landmark: 0
[ INFO] [1591944956.099907360, 1661396775.076756992]: waitForService: Service [/depth_rectifier_manager/load_nodelet] is now available.
[ INFO] [1591944956.100243666, 1661396775.076756992]: waitForService: Service [/depth_manager/load_nodelet] is now available.
[ INFO] [1591944956.545617511, 1661396775.518832629]: Stereo is NOT SUPPORTED
[ INFO] [1591944956.545842654, 1661396775.518832629]: OpenGl version: 4.5 (GLSL 4.5).
[pcl::OrganizedNeighbor::radiusSearch] Input dataset is not from a projective device!
Residual (MSE) 0.000614, using 1248 valid points
[pcl::OrganizedNeighbor::radiusSearch] Input dataset is not from a projective device!
Residual (MSE) 0.000748, using 1444 valid points
[pcl::OrganizedNeighbor::radiusSearch] Input dataset is not from a projective device!
Residual (MSE) 0.001710, using 2303 valid points
[semantic_graph_slam_node-9] process has died [pid 27314, exit code -9, cmd /home/nrc/hd/workspace/ros/semantic_slam_ws/devel/lib/semantic_SLAM/semantic_graph_SLAM_node __name:=semantic_graph_slam_node __log:=/home/nrc/.ros/log/c2c4ddd8-ac79-11ea-96ed-8ca982ff1833/semantic_graph_slam_node-9.log].
log file: /home/nrc/.ros/log/c2c4ddd8-ac79-11ea-96ed-8ca982ff1833/semantic_graph_slam_node-9*.log
```

When it occurs 
```
[pcl::OrganizedNeighbor::radiusSearch] Input dataset is not from a projective device!
Residual (MSE) 0.000614, using 1248 valid points
```
the program is still mapping , so I think the problem is not caused by 'pcl'.

I tried to run the launchfile seperately :
```
ROS_NAMESPACE=camera/color rosrun image_proc image_proc 
roslaunch semantic_SLAM shape.launch  
rosrun semantic_SLAM  semantic_graph_SLAM_node
```

But at the last step i got 'Segmentation fault :
```
add first landmark: 0
Segmentation fault (core dumped)
```
Do you have any idea about it?
Thanks a lot !!!

**Comment by hridaybavle** [comment]
Sorry to hear that. Could you enable verbose: true in file bucket_detector_workspace.yaml which is in the folder cfg and tell send me the output. Also which version of ROS are you using?
I am unable to reproduce your error at my end.

**Comment by He-Rong** [comment]
Hi, I have enabled verbose: true in 'bucket_detector_workspace.yaml ' and I'm using ros-kinetic.
I've tried several times but it still got errors. Here are the outputs of my two runs:
output1:
![2020-06-14 18:07:29](https://user-images.githubusercontent.com/40681527/84846049-84e31b00-b080-11ea-81ef-d959dccfcd4a.png)
output2:
![2020-06-17](https://user-images.githubusercontent.com/40681527/84846082-975d5480-b080-11ea-9b20-323723aa9853.png)
I'm not sure what the problem is.
Thanks ! !

**Comment by hridaybavle** [comment]
Yes it seems to be a g2o library issue. #1 is having the same issue. I will try and see if I can replicate this issue at my end.

**Comment by He-Rong** [comment]
OKKKKK!
THANKS A LOT!

**Comment by hridaybavle** [comment]
Hi, 

I have added a [docker image](https://github.com/hridaybavle/semantic_slam#using-docker-image) of the repo with all the instructions. You can use the docker image for your tests.

**Comment by He-Rong** [comment]
it works.
thanks a lot!!!
