### ISSUE TITLE
Problemas de incompatibilidad de opencv en el bucket detector

### ISSUE THREAD

**Issue by iandresolares** [hridaybavle/semantic_slam#3]
Hola,
he conseguido que ambos paquetes en conjunto (semantic slam y bucket detector) funciones bien en una distro de ubuntu virgen con ROS melodic, sin embargo, cuando migro al pc donde trabajo habitualmente y que tiene ya instaladas dependencias anteriores y demás me encuentro con estos errores referentes a opencv:
![Captura de pantalla de 2021-05-26 11-29-18](https://user-images.githubusercontent.com/62758014/119637503-03f6dc80-be16-11eb-8fcb-b81748cbe0c0.png)
Imagino que se deben a incompatibilidades entre versiones de opencv, podrías confirmarme esto último? Sería posible trabajar con una versión de opencv diferente?
Gracias, un saludo!

**Comment by hridaybavle** [comment]
Hola Andres, 

El bucket_detector es bastante antiguo y no es compatible con las nuevas versiones de opencv como el opencv-4.0. Como vais a usar una nuevas versiones de los detectores, podéis comentar el paquete de bucket_detector con un CATKIN_IGNORE.

Saludos!

**Comment by iandresolares** [comment]
Perfecto! Usaremos directamente otros detectores, el paquete de semantic_SLAM se compila por sí solo sin problemas. Muchas gracias!! Cierro el Issue.
