### ISSUE TITLE
Dataset download failure problem

### ISSUE THREAD

**Issue by kycwx** [hridaybavle/semantic_slam#4]
Hello, when I run the sample code, I always encounter network interruptions or unknown errors at the last moment when downloading the dataset entire_lab_3_rounds.bag. Can you provide a new way to download the bag?

**Comment by hridaybavle** [comment]
Hello, I share with you a new link with the rosbag. Let me know if you can download this one. 

[rosbag](https://uniluxembourg-my.sharepoint.com/:u:/g/personal/hriday_bavle_uni_lu/EbY2ng0GqwpAv033uRKzO0gBhZUEYC4860JuNqTQzRvBUg?e=Df4log)

**Comment by kycwx** [comment]
Thank you very much for your help, the bag link provided this time can be downloaded successfully.
